[package]
name    = "hyprdeck-modules"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hyprdeck-core     = { workspace = true }
chrono            = { workspace = true }
reqwest           = { workspace = true }
nix               = { workspace = true }
freedesktop-icons = { workspace = true }
fn0rd             = { workspace = true }
tokio             = { workspace = true }
tracing           = { workspace = true }
serde             = { workspace = true }
toml              = { workspace = true }
